disabled_rules: # 禁用指定的规则
  - colon
  - comma
  - control_statement
  - line_length
  - identifier_name
  - multiple_closures_with_trailing_closure
opt_in_rules: # 启用指定的规则
  - empty_count
  - missing_docs